server:
  port: 8002
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://172.21.16.11:3306/how_work_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true
    username: how_work_test
    password: how_work_test
    druid:
      initial-size: 10
      min-idle: 1
      max-active: 20
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      validation-query: SELECT x
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      poolPreparedStatements: true
      maxPoolPreparedStatementPerConnectionSize: 20
      remove-abandoned: true
      remove-abandoned-timeout-millis: 5000
      log-abandoned: true

# springboot监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
