# Application
spring:
  application:
    name: api-app
  profiles:
    active: ${profiles.active}
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=120s

mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID,"该类型为未设置主键类型,5, "字符串全局唯一ID"";
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: input

wx:
  miniapp:
    appid: wxebd3588df98ae1a7 #appId
    secret: c88bd845c78c0ddb15a8511f12096022 #密钥
    msgDataFormat: JSON
#    token: 123456 #没用上
#    aesKey: yyyy #没用上
    messageToken: howWorkMessageToken
    accessUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
    messageUrl: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=%s

  pay:
    appId: wxebd3588df98ae1a7 #微信公众号或者小程序等的appid
    mchId: 1604308922 #todo zyc 微信支付商户号
    mchKey: 5b2afa6289e20946fbc850f5937324b0 #todo zyc 微信支付商户密钥
#    keyPath: test/test #todo zyc p12证书的位置，可以指定绝对路径，也可以指定类路径（以classpath:开头）
#    subAppId: #服务商模式下的子商户公众账号ID（不用）
#    subMchId: #服务商模式下的子商户号（不用）
