# Application
spring:
  application:
    name: api-web
  profiles:
    active: ${profiles.active}
  cache:
    type: caffeine
    caffeine:
      spec: initialCapacity=10,maximumSize=200,expireAfterWrite=120s
  jackson:
    default-property-inclusion: non_null
mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID,"该类型为未设置主键类型,5, "字符串全局唯一ID"";
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: input

wx:
#  mp:
#    configs:
#      token: HowWork # 接口配置里的Token值
#      aesKey: c9bOz7tl87unNE8rlokf6mCRolHm26z5hNrdoQdleuo # 接口配置里的EncodingAESKey值
  miniapp:
    appid: wxebd3588df98ae1a7
    secret: c88bd845c78c0ddb15a8511f12096022
    token: 123456
    aesKey: yyyy
    msgDataFormat: JSON
    messageToken: howWorkMessageToken
    accessUrl: https://api.weixin.qq.com/cgi-bin/token?grant_type=client_credential&appid=%s&secret=%s
    messageUrl: https://api.weixin.qq.com/cgi-bin/message/subscribe/send?access_token=%s

img:
  postfix: img,bmp,jpg,png,gif,jpeg
file:
  postfix: docx,doc,pdf,jpg,png

