# Application
spring:
  application:
    name: api-web
  profiles:
    active: dev
  cache:
    type: caffeine

mybatis-plus:
  global-config:
    #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID,"该类型为未设置主键类型,5, "字符串全局唯一ID"";
    db-config:
      logic-delete-field: isDelete
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值(默认为 0)
      id-type: input

wx:
  miniapp:
    appid: wxebd3588df98ae1a7
    secret: c88bd845c78c0ddb15a8511f12096022
    token: 123456
    aesKey: yyyy
    msgDataFormat: JSON
