server:
  port: 8002
# mysql
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
#    url: jdbc:mysql://172.21.16.11:3306/how_work_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
#    username: how_work_test
#    password: how_work_test
    url: jdbc:mysql://localhost:3306/how_work_test?useUnicode=true&characterEncoding=utf-8&useSSL=false&autoReconnect=true&allowMultiQueries=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root

  cos:
    appId: 1301749332
    secretId: AKIDALMUUvExISTJz5nk6LPJ3c37peLtuUXP
    secretKey: o953qTxk2DG8QXTEsSvBFuLUVFyZutd5
    bucketName: howwork-1301749332
    region: ap-beijing
    prefix: https://
    midfix: cos
    suffix: myqcloud.com
    cdnUrl: howwork-1301749332.file.myqcloud.com

  redis:
#      host: 172.21.16.17
#      password: HowWork!
#      database: 1
      host: 192.168.200.128
      database: 1
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8

mybatis-plus:
  configuration:
    #这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
wx:
  miniapp:
    state: trial
